# Generated by Django 5.0.1 on 2024-02-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.RemoveField(
            model_name='projectlinks',
            name='project',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectLinks',
        ),
    ]
