# Generated by Django 5.0.1 on 2024-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0004_rename_categories_categorie_rename_images_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='null', upload_to='media'),
            preserve_default=False,
        ),
    ]
