# Generated by Django 5.0.1 on 2024-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0005_remove_image_image_path_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_image',
            field=models.ImageField(default='test', upload_to='media'),
            preserve_default=False,
        ),
    ]
