# Generated by Django 5.0.1 on 2024-02-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0006_project_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_image',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
