# Generated by Django 5.0.1 on 2024-03-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0008_project_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=300)),
                ('feature_description', models.TextField()),
                ('feature_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_list.project')),
            ],
        ),
    ]
