# Generated by Django 5.0.1 on 2024-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0009_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(null=True, upload_to='static/media/feature'),
        ),
    ]
