# Generated by Django 5.0.1 on 2024-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0010_feature_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
