# Generated by Django 5.0.1 on 2024-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_list', '0011_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
